package com.ade.purifier.server.orm.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _MacInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MacInfo extends CayenneDataObject {

    @Deprecated
    public static final String AREA_PROPERTY = "area";
    @Deprecated
    public static final String CITY_PROPERTY = "city";
    @Deprecated
    public static final String CITY_ID_PROPERTY = "cityId";
    @Deprecated
    public static final String LATITUDE_PROPERTY = "latitude";
    @Deprecated
    public static final String LONGITUDE_PROPERTY = "longitude";
    @Deprecated
    public static final String MAC_PROPERTY = "mac";
    @Deprecated
    public static final String MD5_PROPERTY = "md5";
    @Deprecated
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> AREA = new Property<String>("area");
    public static final Property<String> CITY = new Property<String>("city");
    public static final Property<String> CITY_ID = new Property<String>("cityId");
    public static final Property<Double> LATITUDE = new Property<Double>("latitude");
    public static final Property<Double> LONGITUDE = new Property<Double>("longitude");
    public static final Property<String> MAC = new Property<String>("mac");
    public static final Property<String> MD5 = new Property<String>("md5");
    public static final Property<String> NAME = new Property<String>("name");

    public void setArea(String area) {
        writeProperty("area", area);
    }
    public String getArea() {
        return (String)readProperty("area");
    }

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCityId(String cityId) {
        writeProperty("cityId", cityId);
    }
    public String getCityId() {
        return (String)readProperty("cityId");
    }

    public void setLatitude(Double latitude) {
        writeProperty("latitude", latitude);
    }
    public Double getLatitude() {
        return (Double)readProperty("latitude");
    }

    public void setLongitude(Double longitude) {
        writeProperty("longitude", longitude);
    }
    public Double getLongitude() {
        return (Double)readProperty("longitude");
    }

    public void setMac(String mac) {
        writeProperty("mac", mac);
    }
    public String getMac() {
        return (String)readProperty("mac");
    }

    public void setMd5(String md5) {
        writeProperty("md5", md5);
    }
    public String getMd5() {
        return (String)readProperty("md5");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

}
