package com.ade.purifier.server.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _MacState was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MacState extends CayenneDataObject {

    @Deprecated
    public static final String FILTER_AGE_PROPERTY = "filterAge";
    @Deprecated
    public static final String FILTER_REPLACE_WARN_PROPERTY = "filterReplaceWarn";
    @Deprecated
    public static final String INDOOR_HUMIDITY_PROPERTY = "indoorHumidity";
    @Deprecated
    public static final String INDOOR_PROPER_PROPERTY = "indoorProper";
    @Deprecated
    public static final String INDOOR_TEMPERATURE_PROPERTY = "indoorTemperature";
    @Deprecated
    public static final String MAC_AGE_PROPERTY = "macAge";
    @Deprecated
    public static final String MAC_GEAR_PROPERTY = "macGear";
    @Deprecated
    public static final String MAC_ID_PROPERTY = "macId";
    @Deprecated
    public static final String MAC_RUN_PROPERTY = "macRun";
    @Deprecated
    public static final String MAC_RUN_MODEL_PROPERTY = "macRunModel";
    @Deprecated
    public static final String MAC_TIMING_PROPERTY = "macTiming";
    @Deprecated
    public static final String NIONS_STATE_PROPERTY = "nionsState";
    @Deprecated
    public static final String PANEL_OPEN_WARN_PROPERTY = "panelOpenWarn";
    @Deprecated
    public static final String SMELL_C_PROPERTY = "smellC";
    @Deprecated
    public static final String TIPPING_WARN_PROPERTY = "tippingWarn";
    @Deprecated
    public static final String UPDATE_TIME_PROPERTY = "updateTime";
    @Deprecated
    public static final String UV_STATE_PROPERTY = "uvState";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> FILTER_AGE = new Property<Integer>("filterAge");
    public static final Property<Integer> FILTER_REPLACE_WARN = new Property<Integer>("filterReplaceWarn");
    public static final Property<Integer> INDOOR_HUMIDITY = new Property<Integer>("indoorHumidity");
    public static final Property<Integer> INDOOR_PROPER = new Property<Integer>("indoorProper");
    public static final Property<Integer> INDOOR_TEMPERATURE = new Property<Integer>("indoorTemperature");
    public static final Property<Integer> MAC_AGE = new Property<Integer>("macAge");
    public static final Property<Integer> MAC_GEAR = new Property<Integer>("macGear");
    public static final Property<Integer> MAC_ID = new Property<Integer>("macId");
    public static final Property<Integer> MAC_RUN = new Property<Integer>("macRun");
    public static final Property<Integer> MAC_RUN_MODEL = new Property<Integer>("macRunModel");
    public static final Property<Integer> MAC_TIMING = new Property<Integer>("macTiming");
    public static final Property<Integer> NIONS_STATE = new Property<Integer>("nionsState");
    public static final Property<Integer> PANEL_OPEN_WARN = new Property<Integer>("panelOpenWarn");
    public static final Property<Integer> SMELL_C = new Property<Integer>("smellC");
    public static final Property<Integer> TIPPING_WARN = new Property<Integer>("tippingWarn");
    public static final Property<Date> UPDATE_TIME = new Property<Date>("updateTime");
    public static final Property<Integer> UV_STATE = new Property<Integer>("uvState");

    public void setFilterAge(Integer filterAge) {
        writeProperty("filterAge", filterAge);
    }
    public Integer getFilterAge() {
        return (Integer)readProperty("filterAge");
    }

    public void setFilterReplaceWarn(Integer filterReplaceWarn) {
        writeProperty("filterReplaceWarn", filterReplaceWarn);
    }
    public Integer getFilterReplaceWarn() {
        return (Integer)readProperty("filterReplaceWarn");
    }

    public void setIndoorHumidity(Integer indoorHumidity) {
        writeProperty("indoorHumidity", indoorHumidity);
    }
    public Integer getIndoorHumidity() {
        return (Integer)readProperty("indoorHumidity");
    }

    public void setIndoorProper(Integer indoorProper) {
        writeProperty("indoorProper", indoorProper);
    }
    public Integer getIndoorProper() {
        return (Integer)readProperty("indoorProper");
    }

    public void setIndoorTemperature(Integer indoorTemperature) {
        writeProperty("indoorTemperature", indoorTemperature);
    }
    public Integer getIndoorTemperature() {
        return (Integer)readProperty("indoorTemperature");
    }

    public void setMacAge(Integer macAge) {
        writeProperty("macAge", macAge);
    }
    public Integer getMacAge() {
        return (Integer)readProperty("macAge");
    }

    public void setMacGear(Integer macGear) {
        writeProperty("macGear", macGear);
    }
    public Integer getMacGear() {
        return (Integer)readProperty("macGear");
    }

    public void setMacId(Integer macId) {
        writeProperty("macId", macId);
    }
    public Integer getMacId() {
        return (Integer)readProperty("macId");
    }

    public void setMacRun(Integer macRun) {
        writeProperty("macRun", macRun);
    }
    public Integer getMacRun() {
        return (Integer)readProperty("macRun");
    }

    public void setMacRunModel(Integer macRunModel) {
        writeProperty("macRunModel", macRunModel);
    }
    public Integer getMacRunModel() {
        return (Integer)readProperty("macRunModel");
    }

    public void setMacTiming(Integer macTiming) {
        writeProperty("macTiming", macTiming);
    }
    public Integer getMacTiming() {
        return (Integer)readProperty("macTiming");
    }

    public void setNionsState(Integer nionsState) {
        writeProperty("nionsState", nionsState);
    }
    public Integer getNionsState() {
        return (Integer)readProperty("nionsState");
    }

    public void setPanelOpenWarn(Integer panelOpenWarn) {
        writeProperty("panelOpenWarn", panelOpenWarn);
    }
    public Integer getPanelOpenWarn() {
        return (Integer)readProperty("panelOpenWarn");
    }

    public void setSmellC(Integer smellC) {
        writeProperty("smellC", smellC);
    }
    public Integer getSmellC() {
        return (Integer)readProperty("smellC");
    }

    public void setTippingWarn(Integer tippingWarn) {
        writeProperty("tippingWarn", tippingWarn);
    }
    public Integer getTippingWarn() {
        return (Integer)readProperty("tippingWarn");
    }

    public void setUpdateTime(Date updateTime) {
        writeProperty("updateTime", updateTime);
    }
    public Date getUpdateTime() {
        return (Date)readProperty("updateTime");
    }

    public void setUvState(Integer uvState) {
        writeProperty("uvState", uvState);
    }
    public Integer getUvState() {
        return (Integer)readProperty("uvState");
    }

}
