package com.ade.purifier.server.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _MacStrategy was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MacStrategy extends CayenneDataObject {

    @Deprecated
    public static final String MAC_ID_PROPERTY = "macId";
    @Deprecated
    public static final String OUT_BTIME_PROPERTY = "outBtime";
    @Deprecated
    public static final String OUT_ETIME_PROPERTY = "outEtime";
    @Deprecated
    public static final String SLEEP_BTIME_PROPERTY = "sleepBtime";
    @Deprecated
    public static final String SLEEP_ETIME_PROPERTY = "sleepEtime";
    @Deprecated
    public static final String STANDARD_PROPERTY = "standard";
    @Deprecated
    public static final String UPDATE_TIME_PROPERTY = "updateTime";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> MAC_ID = new Property<Integer>("macId");
    public static final Property<String> OUT_BTIME = new Property<String>("outBtime");
    public static final Property<String> OUT_ETIME = new Property<String>("outEtime");
    public static final Property<String> SLEEP_BTIME = new Property<String>("sleepBtime");
    public static final Property<String> SLEEP_ETIME = new Property<String>("sleepEtime");
    public static final Property<Integer> STANDARD = new Property<Integer>("standard");
    public static final Property<Date> UPDATE_TIME = new Property<Date>("updateTime");

    public void setMacId(Integer macId) {
        writeProperty("macId", macId);
    }
    public Integer getMacId() {
        return (Integer)readProperty("macId");
    }

    public void setOutBtime(String outBtime) {
        writeProperty("outBtime", outBtime);
    }
    public String getOutBtime() {
        return (String)readProperty("outBtime");
    }

    public void setOutEtime(String outEtime) {
        writeProperty("outEtime", outEtime);
    }
    public String getOutEtime() {
        return (String)readProperty("outEtime");
    }

    public void setSleepBtime(String sleepBtime) {
        writeProperty("sleepBtime", sleepBtime);
    }
    public String getSleepBtime() {
        return (String)readProperty("sleepBtime");
    }

    public void setSleepEtime(String sleepEtime) {
        writeProperty("sleepEtime", sleepEtime);
    }
    public String getSleepEtime() {
        return (String)readProperty("sleepEtime");
    }

    public void setStandard(Integer standard) {
        writeProperty("standard", standard);
    }
    public Integer getStandard() {
        return (Integer)readProperty("standard");
    }

    public void setUpdateTime(Date updateTime) {
        writeProperty("updateTime", updateTime);
    }
    public Date getUpdateTime() {
        return (Date)readProperty("updateTime");
    }

}
