package com.ade.purifier.server.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _OutdoorPollution was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OutdoorPollution extends CayenneDataObject {

    @Deprecated
    public static final String CANOP_WINDOW_PROPERTY = "canopWindow";
    @Deprecated
    public static final String HIGH_TEMPERATURE_PROPERTY = "highTemperature";
    @Deprecated
    public static final String LOW_TEMPERATURE_PROPERTY = "lowTemperature";
    @Deprecated
    public static final String MAC_ID_PROPERTY = "macId";
    @Deprecated
    public static final String RAIN_PROPERTY = "rain";
    @Deprecated
    public static final String UPDATE_TIME_PROPERTY = "updateTime";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> CANOP_WINDOW = new Property<Integer>("canopWindow");
    public static final Property<Integer> HIGH_TEMPERATURE = new Property<Integer>("highTemperature");
    public static final Property<Integer> LOW_TEMPERATURE = new Property<Integer>("lowTemperature");
    public static final Property<Integer> MAC_ID = new Property<Integer>("macId");
    public static final Property<Integer> RAIN = new Property<Integer>("rain");
    public static final Property<Date> UPDATE_TIME = new Property<Date>("updateTime");

    public void setCanopWindow(Integer canopWindow) {
        writeProperty("canopWindow", canopWindow);
    }
    public Integer getCanopWindow() {
        return (Integer)readProperty("canopWindow");
    }

    public void setHighTemperature(Integer highTemperature) {
        writeProperty("highTemperature", highTemperature);
    }
    public Integer getHighTemperature() {
        return (Integer)readProperty("highTemperature");
    }

    public void setLowTemperature(Integer lowTemperature) {
        writeProperty("lowTemperature", lowTemperature);
    }
    public Integer getLowTemperature() {
        return (Integer)readProperty("lowTemperature");
    }

    public void setMacId(Integer macId) {
        writeProperty("macId", macId);
    }
    public Integer getMacId() {
        return (Integer)readProperty("macId");
    }

    public void setRain(Integer rain) {
        writeProperty("rain", rain);
    }
    public Integer getRain() {
        return (Integer)readProperty("rain");
    }

    public void setUpdateTime(Date updateTime) {
        writeProperty("updateTime", updateTime);
    }
    public Date getUpdateTime() {
        return (Date)readProperty("updateTime");
    }

}
