package com.ade.purifier.server.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SoftInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SoftInfo extends CayenneDataObject {

    @Deprecated
    public static final String APP_VERSION_PROPERTY = "appVersion";
    @Deprecated
    public static final String CREATE_TIME_PROPERTY = "createTime";
    @Deprecated
    public static final String FILE_NAME_PROPERTY = "fileName";
    @Deprecated
    public static final String FILE_URL_PROPERTY = "fileUrl";
    @Deprecated
    public static final String IS_SENIOR_PROPERTY = "isSenior";
    @Deprecated
    public static final String MD5_PROPERTY = "md5";
    @Deprecated
    public static final String OS_PROPERTY = "os";
    @Deprecated
    public static final String OS_VERSION_PROPERTY = "osVersion";
    @Deprecated
    public static final String SIZE_PROPERTY = "size";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> APP_VERSION = new Property<String>("appVersion");
    public static final Property<Date> CREATE_TIME = new Property<Date>("createTime");
    public static final Property<String> FILE_NAME = new Property<String>("fileName");
    public static final Property<String> FILE_URL = new Property<String>("fileUrl");
    public static final Property<Boolean> IS_SENIOR = new Property<Boolean>("isSenior");
    public static final Property<String> MD5 = new Property<String>("md5");
    public static final Property<String> OS = new Property<String>("os");
    public static final Property<String> OS_VERSION = new Property<String>("osVersion");
    public static final Property<Integer> SIZE = new Property<Integer>("size");

    public void setAppVersion(String appVersion) {
        writeProperty("appVersion", appVersion);
    }
    public String getAppVersion() {
        return (String)readProperty("appVersion");
    }

    public void setCreateTime(Date createTime) {
        writeProperty("createTime", createTime);
    }
    public Date getCreateTime() {
        return (Date)readProperty("createTime");
    }

    public void setFileName(String fileName) {
        writeProperty("fileName", fileName);
    }
    public String getFileName() {
        return (String)readProperty("fileName");
    }

    public void setFileUrl(String fileUrl) {
        writeProperty("fileUrl", fileUrl);
    }
    public String getFileUrl() {
        return (String)readProperty("fileUrl");
    }

    public void setIsSenior(Boolean isSenior) {
        writeProperty("isSenior", isSenior);
    }
    public Boolean getIsSenior() {
        return (Boolean)readProperty("isSenior");
    }

    public void setMd5(String md5) {
        writeProperty("md5", md5);
    }
    public String getMd5() {
        return (String)readProperty("md5");
    }

    public void setOs(String os) {
        writeProperty("os", os);
    }
    public String getOs() {
        return (String)readProperty("os");
    }

    public void setOsVersion(String osVersion) {
        writeProperty("osVersion", osVersion);
    }
    public String getOsVersion() {
        return (String)readProperty("osVersion");
    }

    public void setSize(Integer size) {
        writeProperty("size", size);
    }
    public Integer getSize() {
        return (Integer)readProperty("size");
    }

}
