package com.ade.purifier.server.orm.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SysRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysRole extends CayenneDataObject {

    @Deprecated
    public static final String ROLE_NAME_PROPERTY = "roleName";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ROLE_NAME = new Property<String>("roleName");

    public void setRoleName(String roleName) {
        writeProperty("roleName", roleName);
    }
    public String getRoleName() {
        return (String)readProperty("roleName");
    }

}
