package com.ade.purifier.server.orm.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SysUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysUser extends CayenneDataObject {

    @Deprecated
    public static final String CREATE_TIME_PROPERTY = "createTime";
    @Deprecated
    public static final String EMAIL_PROPERTY = "email";
    @Deprecated
    public static final String PASSWORD_PROPERTY = "password";
    @Deprecated
    public static final String ROLE_PROPERTY = "role";
    @Deprecated
    public static final String USER_NAME_PROPERTY = "userName";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Short> CREATE_TIME = new Property<Short>("createTime");
    public static final Property<String> EMAIL = new Property<String>("email");
    public static final Property<String> PASSWORD = new Property<String>("password");
    public static final Property<Integer> ROLE = new Property<Integer>("role");
    public static final Property<String> USER_NAME = new Property<String>("userName");

    public void setCreateTime(Short createTime) {
        writeProperty("createTime", createTime);
    }
    public Short getCreateTime() {
        return (Short)readProperty("createTime");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setRole(Integer role) {
        writeProperty("role", role);
    }
    public Integer getRole() {
        return (Integer)readProperty("role");
    }

    public void setUserName(String userName) {
        writeProperty("userName", userName);
    }
    public String getUserName() {
        return (String)readProperty("userName");
    }

}
