package com.ade.purifier.server.orm.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SysPage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SysPage extends CayenneDataObject {

    @Deprecated
    public static final String PAGE_PROPERTY = "page";
    @Deprecated
    public static final String ROLE_ID_PROPERTY = "roleId";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> PAGE = new Property<String>("page");
    public static final Property<Integer> ROLE_ID = new Property<Integer>("roleId");

    public void setPage(String page) {
        writeProperty("page", page);
    }
    public String getPage() {
        return (String)readProperty("page");
    }

    public void setRoleId(Integer roleId) {
        writeProperty("roleId", roleId);
    }
    public Integer getRoleId() {
        return (Integer)readProperty("roleId");
    }

}
