package com.ade.purifier.server.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UserInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserInfo extends CayenneDataObject {

    @Deprecated
    public static final String EMAIL_PROPERTY = "email";
    @Deprecated
    public static final String MOBILE_PROPERTY = "mobile";
    @Deprecated
    public static final String PASSWORD_PROPERTY = "password";
    @Deprecated
    public static final String UPDATE_TIME_PROPERTY = "updateTime";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> EMAIL = new Property<String>("email");
    public static final Property<String> MOBILE = new Property<String>("mobile");
    public static final Property<String> PASSWORD = new Property<String>("password");
    public static final Property<Date> UPDATE_TIME = new Property<Date>("updateTime");

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setMobile(String mobile) {
        writeProperty("mobile", mobile);
    }
    public String getMobile() {
        return (String)readProperty("mobile");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setUpdateTime(Date updateTime) {
        writeProperty("updateTime", updateTime);
    }
    public Date getUpdateTime() {
        return (Date)readProperty("updateTime");
    }

}
