package com.ade.purifier.orm.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UserOptHis was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserOptHis extends CayenneDataObject {

    @Deprecated
    public static final String MAC_ID_PROPERTY = "macId";
    @Deprecated
    public static final String OPT_TIME_PROPERTY = "optTime";
    @Deprecated
    public static final String USER_ID_PROPERTY = "userId";
    @Deprecated
    public static final String USER_OPT_PROPERTY = "userOpt";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> MAC_ID = new Property<Integer>("macId");
    public static final Property<Date> OPT_TIME = new Property<Date>("optTime");
    public static final Property<Integer> USER_ID = new Property<Integer>("userId");
    public static final Property<Integer> USER_OPT = new Property<Integer>("userOpt");

    public void setMacId(Integer macId) {
        writeProperty("macId", macId);
    }
    public Integer getMacId() {
        return (Integer)readProperty("macId");
    }

    public void setOptTime(Date optTime) {
        writeProperty("optTime", optTime);
    }
    public Date getOptTime() {
        return (Date)readProperty("optTime");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setUserOpt(Integer userOpt) {
        writeProperty("userOpt", userOpt);
    }
    public Integer getUserOpt() {
        return (Integer)readProperty("userOpt");
    }

}
